#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.local/bin/eww"

if [[ "$1" == "--ff" ]]; then
	${EWW} close-all && rm -rf "$FILE" && firefox &

elif [[ "$1" == "--tg" ]]; then
	${EWW} close-all && rm -rf "$FILE" && telegram-desktop &

elif [[ "$1" == "--dc" ]]; then
	${EWW} close-all && rm -rf "$FILE" && discord &

elif [[ "$1" == "--tr" ]]; then
	${EWW} close-all && rm -rf "$FILE" && kitty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~ &

elif [[ "$1" == "--ge" ]]; then
	${EWW} close-all && rm -rf "$FILE" && spotify &

elif [[ "$1" == "--cd" ]]; then
	${EWW} close-all && rm -rf "$FILE" && emacs &

elif [[ "$1" == "--gp" ]]; then
	${EWW} close-all && rm -rf "$FILE" && gimp &

elif [[ "$1" == "--vb" ]]; then
	${EWW} close-all && rm -rf "$FILE" && virtualbox &

fi
