#!/bin/bash

## Config file for berry WM

## Berry Configs -----------------------------------------------

# Set decoration geometry
berryc border_width 		0
berryc inner_border_width 	0
berryc title_height 		30
#berryc top_gap 			82
berryc edge_gap 			60 20 20 20

# Set decoration colors
berryc focus_color 			434c5e
berryc unfocus_color 		313744
berryc inner_focus_color 	434c5e
berryc inner_unfocus_color 	313744
berryc text_focus_color 	  FFFFFF
berryc text_unfocus_color   313744

# Other options
berryc set_font 			"Iosevka-10"
berryc smart_place 			"true"
berryc draw_text 			"true"
berryc edge_lock 			"true"
berryc json_status 			"true"
berryc decorate_new 		"true"
berryc pointer_interval 	0
berryc manage 				Dialog|Toolbar|Menu|Splash|Utility 

## Autostart Programs ------------------------------------------
# Needed for Java Swing GUIs to work
export _JAVA_AWT_WM_NONREPARENTING=1
xsetroot -cursor_name left_ptr &
xmodmap ~/.Xmodmap &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
 nm-applet &
# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# Enable power management
xfce4-power-manager &

## Enable Super Keys For Menu
sxhkd -c ~/.config/berry/sxhkdrc &

# Enable Super Keys For Menu
#ksuperkey -e 'Super_L=Alt_L|F1' &
#ksuperkey -e 'Super_R=Alt_L|F1' &


# Set/Restore wallpaper
hsetroot -cover /home/jinji/Pictures/walls/misty_mountains.jpg

# Lauch polybar
polybar --config=~/.config/polybar/config berrybar
# Lauch notification daemon
