/usr/bin/prime-offload &
picom -b -c --config ~/.config/picom/config & 
~/.local/bin/lightmode & 
nm-applet & 
xsettingsd &
xfce4-power-manager &
systemctl --user import-environment DISPLAY &
redshift-gtk &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 & 
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
i3
