#!/bin/bash
#based on the wallpaper change to the opposite theme
#WALL= xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP-1/workspace0/last-image
WALL = "test"

if [ $WALL=="test" ] 
then 
	~/.local/bin/darkmode.sh;
elif [ $WALL="!test" ] 
then
	~/.local/bin/lightmode.sh;
elif


#if [ $WALL=='/home/jinji/Pictures/wallpaperflare.com_wallpaper.jpg' ] #light mode
#then 
#	~/.local/bin/darkmode.sh;
#
#elif [ $WALL=='/home/jinji/Pictures/690601.jpg' ] #dark mode
#then
#	~/.local/bin/lightmode.sh;
#fi
#
