#!/bin/bash
#Reference: https://felix-kling.de/blog/2021/linux-toggle-dark-mode.html 
# ヽ(・∀・)ﾉ because I nothing about sed
#change wallpaper
feh --bg-scale ~/Pictures/walls/wallpaperflare.com_wallaper.jpg
#Change icon
# TODO
#Change GTK theme
sed -i s/rose-pine-gtk/rose-pine-dawn-gtk/ ~/.xsettingsd
killall -HUP xsettingsd
# Change Rofi theme
sed -i s/dark.rasi/light.rasi/ ~/.config/rofi/launchers/text/styles/colors.rasi
sed -i s/dark.rasi/light.rasi/ ~/.config/rofi/applets/styles/colors.rasi
#change Kitty colour scheme
kitty +kitten themes --reload-in=all Rosé Pine Dawn
#change zathura theme
# TODO
#polybar
killall -9 polybar 
polybar mybar 

